# Generated by Django 4.0.4 on 2022-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appimports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='address_line1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='address_line2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='contactfirstname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='contactlastname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='customer_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='dealsize',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='month_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='msrp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='order_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='orderdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='orderlinenum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='postal_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='price_each',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='product_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='product_line',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='qtr_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='sales',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='status',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='territory',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='year_id',
            field=models.IntegerField(null=True),
        ),
    ]
