# Generated by Django 4.0.4 on 2022-05-22 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appimports', '0002_alter_salesdata_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='contactfirstname',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='contactlastname',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='dealsize',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='month_id',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='msrp',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='order_num',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='orderdate',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='orderlinenum',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='price_each',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='product_line',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='qtr_id',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='status',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='territory',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='year_id',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='ADDRESSLINE1',
            field=models.CharField(default=21, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='ADDRESSLINE2',
            field=models.CharField(default=23, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='CITY',
            field=models.CharField(default='yeah', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='CONTACTFIRSTNAME',
            field=models.CharField(default='were', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='CONTACTLASTNAME',
            field=models.CharField(default='werew', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='COUNTRY',
            field=models.CharField(default='sdew', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='CUSTOMERNAME',
            field=models.CharField(default='wscvf', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='DEALSIZE',
            field=models.CharField(default='medium', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='MONTH_ID',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='MSRP',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='ORDERDATE',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='ORDERLINENUMBER',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='ORDERNUMBER',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='PHONE',
            field=models.CharField(default=23, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='POSTALCODE',
            field=models.CharField(default=243, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='PRICEEACH',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='PRODUCTCODE',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='PRODUCTLINE',
            field=models.CharField(default=234, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QTR_ID',
            field=models.IntegerField(default=1232),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='QUANTITYORDERED',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='SALES',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='STATE',
            field=models.CharField(default='erfr', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='STATUS',
            field=models.CharField(default='wewe', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='TERRITORY',
            field=models.CharField(default='me', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdata',
            name='YEAR_ID',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
