# Generated by Django 4.0.4 on 2022-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appimports', '0005_alter_salesdata_addressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='ADDRESSLINE1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='ADDRESSLINE2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='CITY',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='CONTACTFIRSTNAME',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='CONTACTLASTNAME',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='COUNTRY',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='CUSTOMERNAME',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='DEALSIZE',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='MONTH_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='MSRP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='ORDERDATE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='ORDERLINENUMBER',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='ORDERNUMBER',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='PHONE',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='POSTALCODE',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='PRICEEACH',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='PRODUCTCODE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='PRODUCTLINE',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QTR_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='QUANTITYORDERED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='SALES',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='STATE',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='STATUS',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='TERRITORY',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='salesdata',
            name='YEAR_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
