# Generated by Django 4.0.4 on 2022-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appimports', '0007_alter_salesdata_customername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdata',
            name='PRODUCTCODE',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
