# Generated by Django 4.0.4 on 2022-05-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appimports', '0008_alter_salesdata_productcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Dollar', models.DecimalField(decimal_places=4, max_digits=9)),
                ('Pound', models.DecimalField(decimal_places=4, max_digits=9)),
                ('Euro', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
    ]
