# Generated by Django 4.0.4 on 2022-05-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appimports', '0009_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='SalesData',
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
